import type { Category, City } from '@/types';

export const CATEGORIES: Category[] = [
  {
    id: '1',
    name: 'Cars',
    nameAr: 'سيارات',
    slug: 'cars',
    icon: 'Car',
    color: '#3B82F6',
    subcategories: [
      { id: '1-1', name: 'Sedan', nameAr: 'سيدان', slug: 'sedan', icon: 'Car' },
      { id: '1-2', name: 'SUV', nameAr: 'دفع رباعي', slug: 'suv', icon: 'Car' },
      { id: '1-3', name: 'Truck', nameAr: 'شاحنة', slug: 'truck', icon: 'Truck' },
      { id: '1-4', name: 'Van', nameAr: 'فان', slug: 'van', icon: 'Bus' },
    ],
  },
  {
    id: '2',
    name: 'Motorcycles',
    nameAr: 'دراجات نارية',
    slug: 'motorcycles',
    icon: 'Bike',
    color: '#EF4444',
    subcategories: [
      { id: '2-1', name: 'Sport', nameAr: 'رياضية', slug: 'sport', icon: 'Bike' },
      { id: '2-2', name: 'Cruiser', nameAr: 'كروزر', slug: 'cruiser', icon: 'Bike' },
      { id: '2-3', name: 'Off-road', nameAr: ' terrain', slug: 'off-road', icon: 'Mountain' },
    ],
  },
  {
    id: '3',
    name: 'Real Estate',
    nameAr: 'عقارات',
    slug: 'real-estate',
    icon: 'Home',
    color: '#10B981',
    subcategories: [
      { id: '3-1', name: 'Apartment', nameAr: 'شقة', slug: 'apartment', icon: 'Building' },
      { id: '3-2', name: 'Villa', nameAr: 'فيلا', slug: 'villa', icon: 'Home' },
      { id: '3-3', name: 'Land', nameAr: 'أرض', slug: 'land', icon: 'Map' },
      { id: '3-4', name: 'Office', nameAr: 'مكتب', slug: 'office', icon: 'Building2' },
    ],
  },
  {
    id: '4',
    name: 'Electronics',
    nameAr: 'إلكترونيات',
    slug: 'electronics',
    icon: 'Smartphone',
    color: '#8B5CF6',
    subcategories: [
      { id: '4-1', name: 'Phones', nameAr: 'هواتف', slug: 'phones', icon: 'Smartphone' },
      { id: '4-2', name: 'Laptops', nameAr: 'لابتوب', slug: 'laptops', icon: 'Laptop' },
      { id: '4-3', name: 'Tablets', nameAr: 'تابلت', slug: 'tablets', icon: 'Tablet' },
      { id: '4-4', name: 'Cameras', nameAr: 'كاميرات', slug: 'cameras', icon: 'Camera' },
    ],
  },
  {
    id: '5',
    name: 'Furniture',
    nameAr: 'أثاث',
    slug: 'furniture',
    icon: 'Sofa',
    color: '#F59E0B',
    subcategories: [
      { id: '5-1', name: 'Living Room', nameAr: 'غرفة معيشة', slug: 'living-room', icon: 'Sofa' },
      { id: '5-2', name: 'Bedroom', nameAr: 'غرفة نوم', slug: 'bedroom', icon: 'Bed' },
      { id: '5-3', name: 'Kitchen', nameAr: 'مطبخ', slug: 'kitchen', icon: 'ChefHat' },
      { id: '5-4', name: 'Office Furniture', nameAr: 'أثاث مكتب', slug: 'office-furniture', icon: 'Armchair' },
    ],
  },
  {
    id: '6',
    name: 'Fashion',
    nameAr: 'أزياء',
    slug: 'fashion',
    icon: 'Shirt',
    color: '#EC4899',
    subcategories: [
      { id: '6-1', name: 'Men', nameAr: 'رجالي', slug: 'men', icon: 'Shirt' },
      { id: '6-2', name: 'Women', nameAr: 'نسائي', slug: 'women', icon: 'Scarf' },
      { id: '6-3', name: 'Kids', nameAr: 'أطفال', slug: 'kids', icon: 'Baby' },
      { id: '6-4', name: 'Accessories', nameAr: 'إكسسوارات', slug: 'accessories', icon: 'Watch' },
    ],
  },
  {
    id: '7',
    name: 'Jobs',
    nameAr: 'وظائف',
    slug: 'jobs',
    icon: 'Briefcase',
    color: '#06B6D4',
    subcategories: [
      { id: '7-1', name: 'Full Time', nameAr: 'دوام كامل', slug: 'full-time', icon: 'Clock' },
      { id: '7-2', name: 'Part Time', nameAr: 'دوام جزئي', slug: 'part-time', icon: 'Clock' },
      { id: '7-3', name: 'Freelance', nameAr: '프리랜서', slug: 'freelance', icon: 'User' },
    ],
  },
  {
    id: '8',
    name: 'Animals',
    nameAr: 'حيوانات',
    slug: 'animals',
    icon: 'Dog',
    color: '#84CC16',
    subcategories: [
      { id: '8-1', name: 'Dogs', nameAr: 'كلاب', slug: 'dogs', icon: 'Dog' },
      { id: '8-2', name: 'Cats', nameAr: 'قطط', slug: 'cats', icon: 'Cat' },
      { id: '8-3', name: 'Birds', nameAr: 'طيور', slug: 'birds', icon: 'Bird' },
      { id: '8-4', name: 'Horses', nameAr: ' horses', slug: 'horses', icon: 'Horse' },
    ],
  },
  {
    id: '9',
    name: 'Sports',
    nameAr: 'رياضة',
    slug: 'sports',
    icon: 'Dumbbell',
    color: '#F97316',
    subcategories: [
      { id: '9-1', name: 'Gym Equipment', nameAr: 'أجهزة رياضية', slug: 'gym-equipment', icon: 'Dumbbell' },
      { id: '9-2', name: 'Bicycles', nameAr: 'دراجات', slug: 'bicycles', icon: 'Bike' },
      { id: '9-3', name: 'Ball Sports', nameAr: 'رياضات الكرة', slug: 'ball-sports', icon: 'Circle' },
    ],
  },
  {
    id: '10',
    name: 'Kids & Baby',
    nameAr: 'أطفال ورضع',
    slug: 'kids-baby',
    icon: 'Baby',
    color: '#D946EF',
    subcategories: [
      { id: '10-1', name: 'Toys', nameAr: 'ألعاب', slug: 'toys', icon: 'Puzzle' },
      { id: '10-2', name: 'Strollers', nameAr: 'عربات أطفال', slug: 'strollers', icon: 'Baby' },
      { id: '10-3', name: 'Baby Clothes', nameAr: 'ملابس أطفال', slug: 'baby-clothes', icon: 'Shirt' },
    ],
  },
  {
    id: '11',
    name: 'Books & Stationery',
    nameAr: 'كتب وقرطاسية',
    slug: 'books-stationery',
    icon: 'BookOpen',
    color: '#7C3AED',
    subcategories: [
      { id: '11-1', name: 'Textbooks', nameAr: 'كتب مدرسية', slug: 'textbooks', icon: 'BookOpen' },
      { id: '11-2', name: 'Novels', nameAr: 'روايات', slug: 'novels', icon: 'BookMarked' },
      { id: '11-3', name: 'Stationery', nameAr: 'قرطاسية', slug: 'stationery', icon: 'Pen' },
    ],
  },
  {
    id: '12',
    name: 'Health & Beauty',
    nameAr: 'صحة وجمال',
    slug: 'health-beauty',
    icon: 'Heart',
    color: '#F43F5E',
    subcategories: [
      { id: '12-1', name: 'Skincare', nameAr: 'العناية بالبشرة', slug: 'skincare', icon: 'Sparkles' },
      { id: '12-2', name: 'Perfumes', nameAr: 'عطور', slug: 'perfumes', icon: 'Droplets' },
      { id: '12-3', name: 'Supplements', nameAr: 'مكملات', slug: 'supplements', icon: 'Pill' },
    ],
  },
  {
    id: '13',
    name: 'Services',
    nameAr: 'خدمات',
    slug: 'services',
    icon: 'Wrench',
    color: '#14B8A6',
    subcategories: [
      { id: '13-1', name: 'Cleaning', nameAr: 'تنظيف', slug: 'cleaning', icon: 'Sparkles' },
      { id: '13-2', name: 'Moving', nameAr: 'نقل', slug: 'moving', icon: 'Truck' },
      { id: '13-3', name: 'Maintenance', nameAr: 'صيانة', slug: 'maintenance', icon: 'Wrench' },
    ],
  },
  {
    id: '14',
    name: 'Food & Agriculture',
    nameAr: 'غذاء وزراعة',
    slug: 'food-agriculture',
    icon: 'Apple',
    color: '#22C55E',
    subcategories: [
      { id: '14-1', name: 'Fresh Produce', nameAr: 'خضروات وفواكه', slug: 'fresh-produce', icon: 'Apple' },
      { id: '14-2', name: 'Seeds', nameAr: 'بذور', slug: 'seeds', icon: 'Sprout' },
      { id: '14-3', name: 'Fertilizers', nameAr: 'سماد', slug: 'fertilizers', icon: 'Leaf' },
    ],
  },
  {
    id: '15',
    name: 'Construction Materials',
    nameAr: 'مواد بناء',
    slug: 'construction-materials',
    icon: 'Hammer',
    color: '#A855F7',
    subcategories: [
      { id: '15-1', name: 'Bricks', nameAr: 'طوب', slug: 'bricks', icon: 'Box' },
      { id: '15-2', name: 'Cement', nameAr: 'أسمنت', slug: 'cement', icon: 'HardHat' },
      { id: '15-3', name: 'Tiles', nameAr: 'بلاط', slug: 'tiles', icon: 'LayoutGrid' },
    ],
  },
  {
    id: '16',
    name: 'Musical Instruments',
    nameAr: 'آلات موسيقية',
    slug: 'musical-instruments',
    icon: 'Music',
    color: '#EA580C',
    subcategories: [
      { id: '16-1', name: 'Guitar', nameAr: 'جيتار', slug: 'guitar', icon: 'Music' },
      { id: '16-2', name: 'Piano', nameAr: 'بيانو', slug: 'piano', icon: 'Music' },
      { id: '16-3', name: 'Drums', nameAr: 'طبول', slug: 'drums', icon: 'Music' },
    ],
  },
  {
    id: '17',
    name: 'Gaming',
    nameAr: 'ألعاب',
    slug: 'gaming',
    icon: 'Gamepad2',
    color: '#6366F1',
    subcategories: [
      { id: '17-1', name: 'Consoles', nameAr: 'أجهزة ألعاب', slug: 'consoles', icon: 'Gamepad2' },
      { id: '17-2', name: 'PC Gaming', nameAr: 'ألعاب كمبيوتر', slug: 'pc-gaming', icon: 'Monitor' },
      { id: '17-3', name: 'Accessories', nameAr: 'إكسسوارات', slug: 'accessories', icon: 'Joystick' },
    ],
  },
  {
    id: '18',
    name: 'Wedding & Events',
    nameAr: 'أعراس ومناسبات',
    slug: 'wedding-events',
    icon: 'PartyPopper',
    color: '#F59E0B',
    subcategories: [
      { id: '18-1', name: 'Dresses', nameAr: 'فساتين', slug: 'dresses', icon: 'Sparkles' },
      { id: '18-2', name: 'Decoration', nameAr: 'ديكور', slug: 'decoration', icon: 'PartyPopper' },
      { id: '18-3', name: 'Rentals', nameAr: 'تأجير', slug: 'rentals', icon: 'Calendar' },
    ],
  },
  {
    id: '19',
    name: 'Travel',
    nameAr: 'سفر',
    slug: 'travel',
    icon: 'Plane',
    color: '#0EA5E9',
    subcategories: [
      { id: '19-1', name: 'Flights', nameAr: 'رحلات', slug: 'flights', icon: 'Plane' },
      { id: '19-2', name: 'Hotels', nameAr: 'فنادق', slug: 'hotels', icon: 'Hotel' },
      { id: '19-3', name: 'Packages', nameAr: 'باقات', slug: 'packages', icon: 'Package' },
    ],
  },
  {
    id: '20',
    name: 'Other',
    nameAr: 'أخرى',
    slug: 'other',
    icon: 'MoreHorizontal',
    color: '#6B7280',
    subcategories: [
      { id: '20-1', name: 'Miscellaneous', nameAr: 'متنوعة', slug: 'miscellaneous', icon: 'Package' },
    ],
  },
];

export const CITIES: City[] = [
  { id: '1', name: 'Riyadh', nameAr: 'الرياض', slug: 'riyadh', imageUrl: '/images/cities/riyadh.jpg', listingsCount: 0 },
  { id: '2', name: 'Jeddah', nameAr: 'جدة', slug: 'jeddah', imageUrl: '/images/cities/jeddah.jpg', listingsCount: 0 },
  { id: '3', name: 'Mecca', nameAr: 'مكة المكرمة', slug: 'mecca', imageUrl: '/images/cities/mecca.jpg', listingsCount: 0 },
  { id: '4', name: 'Medina', nameAr: 'المدينة المنورة', slug: 'medina', imageUrl: '/images/cities/medina.jpg', listingsCount: 0 },
  { id: '5', name: 'Dammam', nameAr: 'الدمام', slug: 'dammam', imageUrl: '/images/cities/dammam.jpg', listingsCount: 0 },
  { id: '6', name: 'Khobar', nameAr: 'الخبر', slug: 'khobar', imageUrl: '/images/cities/khobar.jpg', listingsCount: 0 },
  { id: '7', name: 'Tabuk', nameAr: 'تبوك', slug: 'tabuk', imageUrl: '/images/cities/tabuk.jpg', listingsCount: 0 },
  { id: '8', name: 'Abha', nameAr: 'أبها', slug: 'abha', imageUrl: '/images/cities/abha.jpg', listingsCount: 0 },
  { id: '9', name: 'Buraidah', nameAr: 'بريدة', slug: 'buraidah', imageUrl: '/images/cities/buraidah.jpg', listingsCount: 0 },
  { id: '10', name: 'Khamis Mushait', nameAr: 'خميس مشيط', slug: 'khamis-mushait', imageUrl: '/images/cities/khamis-mushait.jpg', listingsCount: 0 },
  { id: '11', name: 'Hafr Al-Batin', nameAr: 'حفر الباطن', slug: 'hafr-al-batin', imageUrl: '/images/cities/hafr-al-batin.jpg', listingsCount: 0 },
  { id: '12', name: 'Jubail', nameAr: 'الجبيل', slug: 'jubail', imageUrl: '/images/cities/jubail.jpg', listingsCount: 0 },
];

export const ANIMAL_TYPES = [
  { id: '1', name: 'Dogs', nameAr: 'كلاب', slug: 'dogs', icon: 'Dog' },
  { id: '2', name: 'Cats', nameAr: 'قطط', slug: 'cats', icon: 'Cat' },
  { id: '3', name: 'Birds', nameAr: 'طيور', slug: 'birds', icon: 'Bird' },
  { id: '4', name: 'Horses', nameAr: ' horses', slug: 'horses', icon: 'Horse' },
  { id: '5', name: 'Sheep', nameAr: 'خراف', slug: 'sheep', icon: 'Sheep' },
  { id: '6', name: 'Camels', nameAr: 'إبل', slug: 'camels', icon: 'Camel' },
  { id: '7', name: 'Goats', nameAr: 'ماعز', slug: 'goats', icon: 'Goat' },
  { id: '8', name: 'Rabbits', nameAr: 'أرانب', slug: 'rabbits', icon: 'Rabbit' },
  { id: '9', name: 'Fish', nameAr: 'أسماك', slug: 'fish', icon: 'Fish' },
  { id: '10', name: 'Other', nameAr: 'أخرى', slug: 'other-animal', icon: 'PawPrint' },
];

export const CRAFTSMEN_TYPES = [
  { id: '1', name: 'Electrician', nameAr: ' كهربائي', slug: 'electrician', icon: 'Zap' },
  { id: '2', name: 'Plumber', nameAr: 'سباك', slug: 'plumber', icon: 'Droplets' },
  { id: '3', name: 'Carpenter', nameAr: 'نجار', slug: 'carpenter', icon: 'Hammer' },
  { id: '4', name: 'Painter', nameAr: 'دهان', slug: 'painter', icon: 'Paintbrush' },
  { id: '5', name: 'AC Technician', nameAr: 'فني تكييف', slug: 'ac-technician', icon: 'Wind' },
  { id: '6', name: 'Mechanic', nameAr: 'ميكانيكي', slug: 'mechanic', icon: 'Wrench' },
  { id: '7', name: 'Tailor', nameAr: 'خياط', slug: 'tailor', icon: 'Scissors' },
  { id: '8', name: 'Photographer', nameAr: 'مصور', slug: 'photographer', icon: 'Camera' },
  { id: '9', name: 'Chef', nameAr: 'طباخ', slug: 'chef', icon: 'ChefHat' },
  { id: '10', name: 'Tiler', nameAr: 'بلاط', slug: 'tiler', icon: 'LayoutGrid' },
  { id: '11', name: 'Blacksmith', nameAr: 'حداد', slug: 'blacksmith', icon: 'Anvil' },
  { id: '12', name: 'Jeweler', nameAr: 'صائغ', slug: 'jeweler', icon: 'Gem' },
];

export const SORT_OPTIONS = [
  { id: 'newest', name: 'الأحدث', nameEn: 'Newest' },
  { id: 'oldest', name: 'الأقدم', nameEn: 'Oldest' },
  { id: 'price_low', name: 'السعر: من الأقل', nameEn: 'Price: Low to High' },
  { id: 'price_high', name: 'السعر: من الأعلى', nameEn: 'Price: High to Low' },
  { id: 'most_viewed', name: 'الأكثر مشاهدة', nameEn: 'Most Viewed' },
  { id: 'most_liked', name: 'الأكثر إعجاباً', nameEn: 'Most Liked' },
  { id: 'nearest', name: 'الأقرب', nameEn: 'Nearest' },
];

export const CONDITION_OPTIONS = [
  { id: 'new', name: 'جديد', nameEn: 'New', color: 'bg-green-100 text-green-800' },
  { id: 'like_new', name: 'كالجديد', nameEn: 'Like New', color: 'bg-blue-100 text-blue-800' },
  { id: 'used', name: 'مستعمل', nameEn: 'Used', color: 'bg-yellow-100 text-yellow-800' },
];
